
import { Translation } from './types';

// The provided pool of API keys for rotation
export const YOUTUBE_API_KEYS = [import.meta.env.VITE_YOUTUBE_API_KEY].filter(Boolean);

// Default to the first key
export const DEFAULT_API_KEY = YOUTUBE_API_KEYS[0];
export const YOUTUBE_API_KEY = YOUTUBE_API_KEYS[0];

export const COUNTRY_TIMEZONES: Record<string, string> = {
  // Arab World
  'EG': 'Africa/Cairo',
  'SA': 'Asia/Riyadh',
  'AE': 'Asia/Dubai',
  'KW': 'Asia/Kuwait',
  'QA': 'Asia/Qatar',
  'BH': 'Asia/Bahrain',
  'OM': 'Asia/Muscat',
  'LB': 'Asia/Beirut',
  'JO': 'Asia/Amman',
  'IQ': 'Asia/Baghdad',
  'DZ': 'Africa/Algiers',
  'MA': 'Africa/Casablanca',
  'TN': 'Africa/Tunis',
  'LY': 'Africa/Tripoli',
  'SD': 'Africa/Khartoum',
  'YE': 'Asia/Aden',
  'PS': 'Asia/Gaza',
  'SY': 'Asia/Damascus',
  'MR': 'Africa/Nouakchott',
  'SO': 'Africa/Mogadishu',

  // Europe
  'GB': 'Europe/London',
  'FR': 'Europe/Paris',
  'DE': 'Europe/Berlin',
  'IT': 'Europe/Rome',
  'ES': 'Europe/Madrid',
  'NL': 'Europe/Amsterdam',
  'BE': 'Europe/Brussels',
  'SE': 'Europe/Stockholm',
  'TR': 'Europe/Istanbul',
  'RU': 'Europe/Moscow',
  'CH': 'Europe/Zurich',
  'AT': 'Europe/Vienna',

  // Americas
  'US': 'America/New_York',
  'CA': 'America/Toronto',
  'MX': 'America/Mexico_City',
  'BR': 'America/Sao_Paulo',
  'AR': 'America/Argentina/Buenos_Aires',
  'CL': 'America/Santiago',
  'CO': 'America/Bogota',

  // Asia & Oceania
  'CN': 'Asia/Shanghai',
  'JP': 'Asia/Tokyo',
  'KR': 'Asia/Seoul',
  'IN': 'Asia/Kolkata',
  'PK': 'Asia/Karachi',
  'ID': 'Asia/Jakarta',
  'MY': 'Asia/Kuala_Lumpur',
  'SG': 'Asia/Singapore',
  'AU': 'Australia/Sydney',
  'NZ': 'Pacific/Auckland',

  // Africa
  'ZA': 'Africa/Johannesburg',
  'NG': 'Africa/Lagos',
  'KE': 'Africa/Nairobi',
  'GH': 'Africa/Accra'
};

export const CPM_RATES: Record<string, { min: number, max: number }> = {
  'US': { min: 4, max: 15 },
  'GB': { min: 3, max: 10 },
  'DE': { min: 3, max: 12 },
  'CA': { min: 3, max: 10 },
  'AU': { min: 3, max: 10 },
  'EG': { min: 0.5, max: 2 },
  'SA': { min: 1.5, max: 5 },
  'AE': { min: 2, max: 6 },
  'KW': { min: 1.5, max: 5 },
  'QA': { min: 2, max: 6 },
  'DEFAULT': { min: 1, max: 4 }
};

export const VPH_TIPS_EXPANDED: Record<string, Record<'en' | 'ar', string>> = {
  viral: {
    en: "Performance is exceptional! Create a follow-up video immediately to capitalize on this traffic loop.",
    ar: "أداء استثنائي! قم بإنشاء فيديو متابعة فوراً لاستغلال هذه الحركة."
  },
  rising: {
    en: "Strong traction. Reply to every comment to trigger the algorithm's engagement signals.",
    ar: "زخم جيد. قم بالرد على كل تعليق لتنشيط إشارات التفاعل في الخوارزمية."
  },
  stable: {
    en: "Consistent traffic. Ensure your end-screens point to your newest videos to keep viewers.",
    ar: "حركة مستقرة. تأكد من أن شاشات النهاية تشير إلى فيديوهاتك الجديدة."
  },
  slow: {
    en: "Velocity is low. Try A/B testing a new thumbnail or updating the title to be more clickable.",
    ar: "السرعة منخفضة. جرب تغيير الصورة المصغرة أو تحديث العنوان ليكون أكثر جاذبية للنقر."
  }
};



export const TRANSLATIONS: Record<'en' | 'ar', Translation> = {
  // ... (Existing translations kept same)
  en: {
    home: "Dashboard",
    channelAnalytics: "Channel Overview",
    videoAnalytics: "Video Inspector",
    seoTools: "Smart SEO",
    earningsLab: "Earnings Lab",
    liveCounter: "Live Counter",
    vphTool: "VPH Calculator",
    ideaGenerator: "Content Ideas",
    competitorAnalysis: "Competitor Spy",
    outliers: "Outlier Detection",
    planner: "Growth Plan",
    audienceDeepDive: "Audience DNA",
    audienceInsights: "Not Used",
    imageGenerator: "Nano Banana Studio",
    scriptWriter: "Expert Script Writer",
    history: "Records & History",
    guidelines: "Docs & Guides",
    trendForecasting: "Trend Forecasting",
    thumbnailSimulator: "Thumbnail A/B Sim",
    videoTiming: "Video Micro-Timing",
    globalTiming: "Global Timing Atlas",
    searchPlaceholder: "Paste Channel/Video URL or ID...",
    analyze: "Analyze",
    views: "Views",
    subscribers: "Subscribers",
    videos: "Videos",
    country: "Country",
    created: "Joined",
    channelAge: "Channel Age",
    description: "Description",
    keywords: "Tags & Keywords",
    copy: "Copy",
    copied: "Copied!",
    subscribe: "Subscribe",
    engagementRate: "Engagement Rate",
    vph: "Views Per Hour (Lifetime)",
    estimatedEarnings: "Estimated Earnings",
    seoScore: "SEO Score",
    titleGenerator: "Title Generator",
    moneyCalculator: "Profit Calculator",
    days: "days",
    months: "months",
    years: "years",
    ago: "ago",
    loading: "Processing Data...",
    error: "Error fetching data",
    channelNotFund: "Channel not found",
    videoNotFound: "Video not found",
    enterUrl: "Enter a valid YouTube URL",
    generate: "Generate",
    recommendation: "Recommendation",
    good: "Good",
    bad: "Needs Improvement",
    excellent: "Excellent",
    calcEarnings: "Calculate Potential",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    min: "Min",
    max: "Max",
    avg: "Avg",
    compare: "Compare Channels",
    vs: "VS",
    bestTime: "Best Time to Post",
    exportPdf: "Export Plan",
    exportImage: "Export as Image",
    weeklyPlan: "Weekly Strategy",
    potential: "Potential",
    likes: "Likes",
    comments: "Comments",
    descWords: "Description Words",
    perDay: "/ day",
    targetMarket: "Target Market",
    avgViewsPerVid: "views/vid",
    publishedLabel: "Published",
    ageLabel: "Age",
    targetKeywords: "Target Keywords",
    optimizedTitles: "Optimized Titles (50-60 chars)",
    copyAllKeywords: "Copy All Keywords",
    charsLabel: "characters",
    useAiCheck: "Use Gemini 3 Pro AI",
    healthScore: "Channel Health",
    seo_title_length: "Title Length",
    seo_tag_depth: "Tag Depth",
    seo_description: "Description Depth",
    seo_synergy: "Keyword Synergy",
    seo_chars: "chars",
    seo_tags_used: "tags used",
    seo_words: "words",
    seo_matches: "matches",
    analyzeVph: "Calculate Velocity",
    currentVelocity: "Current Velocity",
    trendAnalysis: "Trend Analysis",
    optimizationTips: "Optimization Tips",
    totalWatchTime: "Est. Total Watch Time",
    trend_viral: "Viral / Exploding 🚀",
    trend_rising: "Rising / Trending 🔥",
    trend_stable: "Stable / Evergreen ⚖️",
    trend_slow: "Slow / Decelerating 📉",
    tip_viral: "Performance is exceptional! Create a follow-up video immediately to capitalize on this traffic loop.",
    tip_rising: "Strong traction. Reply to every comment to trigger the algorithm's engagement signals.",
    tip_stable: "Consistent traffic. Ensure your end-screens point to your newest videos to keep viewers.",
    tip_slow: "Velocity is low. Try A/B testing a new thumbnail or updating the title to be more clickable.",
    nicheIdentified: "Niche Identified",
    topCompetitors: "Top Competitors",
    strategicFocus: "Strategic Focus Areas",
    competitorPlaceholder: "Enter your channel link. AI will identify your niche and reveal real competitors.",
    selectToCompare: "Select to Benchmark",
    benchmark: "Benchmark Selected",
    comparisonTable: "Comparison Matrix",
    metric_label: "Metric",
    you_label: "(You)",
    engagement_label: "Engagement Rate",
    avg_views_label: "Avg Views/Video",
    primaryMarket: "Primary Market",
    highEngagement: "High Engagement Window",
    preciseTime: "Precise Upload Time",
    audienceDesc: "Discover optimal post times and analyze the creator's upload schedule with timezone precision.",
    globalUnset: "Global / Unset",
    fullSchedule: "Full Weekly Schedule",
    scheduleTracker: "Creator Schedule Tracker",
    consistencyScore: "Consistency Score",
    predictedUpload: "Next Predicted Upload",
    commonUploadTimes: "Common Upload Times",
    timezoneDetected: "Timezone Detected",
    uploadHabits: "Upload Habits",
    consistent: "Consistent",
    random: "Random",
    lvl_viral: "Viral 🔥",
    lvl_excellent: "Excellent 🚀",
    lvl_good: "Good ✅",
    lvl_weak: "Average ⚠️",
    predictedAudience: "Predicted Audience",
    male: "Male",
    female: "Female",
    topDayLabel: "BEST DAY",
    weeklyProtocol: "Weekly Growth Protocol",
    focusGoal: "Focus Goal",
    weeklyCommitment: "I commit to executing this plan to grow my channel.",
    startPlan: "Initialize Your Growth Plan",
    planDesc: "Enter your channel link. The system will analyze weaknesses and generate a weekly task schedule.",
    goldenRatio: "The 'Golden Ratio'",
    noOutliers: "No significant outliers detected.",
    outlierDesc: "Discover videos that performed 2x-10x better than the channel average.",
    trendingKeywords: "Trending Keywords",
    aiIdeas: "AI Generated Ideas",
    useAiLabel: "Use Gemini 3 Pro AI",
    contentDepth: "Content Depth",
    minRevenue: "Min Revenue",
    maxRevenue: "Max Revenue",
    smartAlgo: "Smart Algorithm Analysis",
    algoDesc: "Based on the channel location and content category, a custom CPM was generated.",
    titleAnalysis: "Title Analysis",
    cpmLabel: "Est. CPM",
    total: "Total",
    lifetime: "Lifetime",
    videoType: "Video",
    channelType: "Channel",
    viewOnYoutube: "View on YouTube",
    healthScoreTitle: "Channel Health & Ecosystem",
    consistency: "Consistency",
    engagement: "Engagement",
    viralPotential: "Viral Potential",
    action_ideas: "Content Ideas",
    action_competitors: "Competitor Spy",
    action_outliers: "Find Outliers",
    action_planner: "Growth Plan",
    view_deep_analytics: "Deep Analytics",
    shortsAnalysis: "Shorts Analysis",
    shortsEngagementDesc: "Shorts require higher engagement rates (>5%) to hit the Shorts Feed algorithm.",
    monetizationStatus: "Monetization Status",
    eligible: "Likely Monetized",
    notEligible: "Requirements Not Met",
    ypp_requirements: "YPP Requirements",
    req_subs_title: "1,000 Subscribers",
    req_hours_title: "4,000 Public Watch Hours",
    req_hours_title_short: "4,000 Hours",
    req_shorts_title: "10M Valid Shorts Views",
    or: "OR",
    met: "Met",
    not_met: "Not Met",
    chat_welcome: "Hello! I'm Muthaqaf AI. Ask me about YouTube trends, analyze your channel, or anything on the web!",
    chat_placeholder: "Ask about your channel, CPM rates, or strategy...",
    chat_assistant: "Muthaqaf AI",
    chat_thinking: "Thinking & Searching...",
    mode_fast: "Fast",
    mode_think: "Thinker",
    mode_search: "Search",
    chat_copy: "Copy",
    chat_reply: "Reply",
    chat_quote: "Quote Selection",
    chat_replying_to: "Replying to...",
    chat_clear_confirm: "Are you sure you want to clear the chat history?",
    chat_history_label: "AI Chat",
    chat_new_chat: "New Conversation",
    chat_delete_msg: "Delete Message",
    brain_mode: "Brain Mode (Deep Scan)",
    brain_active: "MASTERMIND ACTIVE",
    deep_scan_start: "Initializing Deep Scan Protocol...",
    fetching_channel: "Fetching Channel Architecture...",
    fetching_videos: "Analyzing Latest Content Velocity...",
    calculating_growth: "Computing Growth Algorithms...",
    report_ready: "Strategic Report Generated.",
    download_report: "Download Report",
    img_gen_title: "Nano Banana Studio",
    img_gen_desc: "Create vibrant, viral-ready YouTube thumbnails and images using the Gemini 2.5 Flash Image Model.",
    img_tab_generate: "Generate",
    img_tab_edit: "Magic Editor",
    img_upload_label: "Upload Base Image",
    img_upload_desc: "This will be your background or main subject.",
    img_add_asset: "Add Element / Object",
    img_add_asset_desc: "Upload a secondary image to blend into the scene.",
    img_add_asset_2: "Add Another Element",
    chat_img_normal: "Normal Image",
    chat_img_thumbnail: "YouTube Thumbnail",
    chat_img_generating: "Processing...",
    chat_img_placeholder: "Describe the image or the edit you want...",
    download_image: "Download Image",
    select_ratio: "Select Target Ratio",
    export_options: "Export Options",
    export_2k: "Upscale to 2K (QHD)",
    export_4k: "Upscale to 4K (UHD)",
    enhancing_label: "Enhancing & Upscaling...",
    download_ready: "Download Ready",
    script_title: "Expert Script Writer",
    script_desc: "Generate human-quality, SEO-optimized scripts in any language (specialized in Egyptian Slang).",
    script_placeholder: "Enter video title, topic, or idea...",
    script_duration_label: "Target Duration",
    script_tone_label: "Script Tone",
    script_lang_label: "Language / Dialect",
    script_hook_label: "Opening Hook Strategy",
    script_custom_hook_placeholder: "Type your specific opening line here...",
    script_tone_serious: "Serious & Professional",
    script_tone_funny: "Funny & Engaging",
    script_tone_story: "Storytelling",
    script_tone_educational: "Educational (Step-by-Step)",
    script_tone_motivational: "Motivational & Inspiring",
    script_tone_sarcastic: "Sarcastic & Witty",
    script_tone_mysterious: "Mysterious & Suspenseful",
    script_tone_emotional: "Emotional",
    script_tone_fast: "Fast-paced (TikTok Style)",
    script_tone_calm: "Calm & Soothing",
    script_tone_controversial: "Controversial/Debate",
    script_tone_dramatic: "Dramatic",
    script_tone_casual: "Casual / Vlog",
    script_tone_professional: "Corporate / Professional",
    script_tone_urgent: "Urgent / Warning",
    script_hook_none: "Standard / None",
    script_hook_question: "Shocking Question",
    script_hook_fact: "Surprising Fact",
    script_hook_neg: "Negative Urgency (Stop doing this)",
    script_hook_story: "Story Opener (It was 3 AM...)",
    script_hook_compare: "Comparison (X vs Y)",
    script_lang_egy: "Arabic (Egyptian - Masri)",
    script_lang_sa: "Arabic (Saudi - Khaliji)",
    script_lang_shami: "Arabic (Levantine - Shami)",
    script_lang_maghreb: "Arabic (Maghrebi - Darija)",
    script_lang_iraqi: "Arabic (Iraqi)",
    script_lang_yemen: "Arabic (Yemeni)",
    script_lang_fusha: "Arabic (Modern Standard)",
    script_lang_en: "English (Global)",
    script_lang_es: "Spanish",
    script_lang_fr: "French",
    script_lang_de: "German",
    script_lang_hi: "Hindi",
    script_lang_ru: "Russian",
    script_lang_pt: "Portuguese",
    script_lang_zh: "Chinese",
    script_lang_jp: "Japanese",
    script_lang_kr: "Korean",
    script_lang_tr: "Turkish",
    script_duration_short: "Short (1-3 min)",
    script_duration_medium: "Medium (5-8 min)",
    script_duration_long: "Long (10-20 min)",
    script_generating: "Writing Script...",
    script_section_title: "SEO Optimized Title",
    script_section_desc: "SEO Description",
    script_section_body: "Video Script",
    script_copy_all: "Copy All",
    script_show_notes: "Show Director Notes",
    script_hide_notes: "Hide Director Notes",
    aud_segments: "Audience Segments",
    aud_new: "New Viewers",
    aud_casual: "Casual Viewers",
    aud_loyal: "Returning/Loyal",
    aud_formats: "Format Preference",
    aud_devices: "Device Usage",
    aud_geo: "Top Geographies",
    aud_online: "When Viewers Are Online",
    aud_also_watch: "Channels They Also Watch",
    aud_growth_drivers: "Growth Drivers",
    aud_desc: "Deep analysis of viewer segments, behavior, and demographics.",
    history_title: "Saved Records",
    history_desc: "Permanent record of all your analyses. Never deleted unless you choose to.",
    clear_history: "Clear All History",
    no_history: "No records found yet. Start analyzing!",
    filter_all: "All Records",
    view_result: "View Result",
    delete: "Delete",
    renew_record: "Renew 1 Year",
    expires_in: "Expires in:",
    days_left: "days left",
    record_renewed: "Record Renewed!",
    tooltip_live_input: "Accepts Channel URL, ID, or Handle (e.g., @name).",
    tooltip_sub_count: "Direct connection to YouTube API. Updates every 1 second automatically.",
    tooltip_channel_stats: "Total accumulated statistics since channel inception.",
    tooltip_channel_age: "Precise calculation from the 'publishedAt' date metadata.",
    tooltip_video_input: "Accepts Video URL, ID, or Shorts link.",
    tooltip_vph: "Views Per Hour: A velocity metric calculated by dividing Total Views by Hours since upload. Indicates viral potential.",
    tooltip_engagement: "Interaction Score: (Likes + Comments) / Views. Measures how active your audience is.",
    tooltip_seo_score: "Algorithmic analysis of title length, power words, and clickability.",
    tooltip_tags: "Hidden metadata tags extracted from the video source code.",
    tooltip_earnings_input: "Enter a Video or Channel URL to auto-detect niche and location.",
    tooltip_cpm: "Cost Per Mille: Estimated revenue per 1,000 views based on viewer location (GDP) and content niche (Ad rates).",
    tooltip_est_earnings: "Projected Revenue: Assumes ~60% of views are monetized. Actual earnings vary by watch time and ad types.",
    tooltip_seo_generator: "Generates high-CTR titles using viral linguistic patterns and keyword placement.",
    tooltip_watch_time: "Aggregate time spent by all viewers watching this video (Views × Duration).",
    tooltip_min_rev: "Conservative estimate based on low fill rates.",
    tooltip_max_rev: "Optimistic estimate assuming high retention and premium ads.",
    tooltip_algo_calc: "How this was calculated: Views × Monetized Playback Rate (est. 60%) × (CPM ÷ 1000).",
    tooltip_trend_logic: "Trend is determined by correlating the current VPH velocity with the video's age.",
    vt_exact_pub: "Exact Publication Time",
    vt_exact_pub_desc: "Analyzes the exact millisecond the video was indexed by Google servers.",
    vt_viewer_flow: "Audience Flow Simulator",
    vt_viewer_flow_desc: "Algorithmic estimation of real-time viewer arrival since upload.",
    vt_peak_time: "Predicted Traffic Peak",
    vt_retention_window: "Prime Retention Window",
    vt_algo_verdict: "Algorithmic Timing Verdict",
    vt_pacing_score: "Velocity Pacing Score",
    vt_viral_probability: "Viral Velocity Probability",
    prompt_lib_title: "Neural Engine & Prompt Library",
    script_duration_15s: "15 Seconds (Shorts)",
    script_duration_60s: "60 Seconds (Standard)",
    script_duration_5m: "5 Minutes (Deep Dive)",
    script_duration_10m: "10 Minutes (Documentary)",
    script_tone_energetic: "Energetic & Hype",
    script_tone_professional_calm: "Professional & Calm",
    script_tone_storytelling_emotional: "Storytelling & Emotional",
    script_tone_educational_clear: "Educational & Clear",
    script_hook_curiosity: "Curiosity Question",
    script_hook_shocking: "Shocking Fact",
    script_hook_result: "Result First",
    script_hook_story_media: "In Media Res (Story)",
    script_seo_low: "Low",
    script_seo_balanced: "Balanced",
    script_seo_high: "High",
    script_neural_engine: "Neural Script Engine",
    script_viral_2026: "Viral Scriptwriter 2026",
    planner_goal: "Growth Goal",
    planner_style: "Content Style",
    planner_style_mixed: "Mixed (Shorts + Long)",
    planner_style_shorts: "Shorts Only",
    planner_style_long: "Long-form Only",
    planner_military_grade: "Military Grade",
    planner_exponential: "Exponential Growth",
    planner_secure: "Secure Analysis",
    seo_focus: "SEO Focus",
    seo_region: "Target Region",
    seo_region_global: "Global",
    seo_region_mena: "MENA",
    seo_region_us_eu: "US & EU",
    seo_region_asia: "Asia",
    seo_engine: "Neural SEO Engine",
    idea_niche: "Niche",
    idea_platform: "Platform",
    idea_trending: "Trending Now",
    idea_evergreen: "Evergreen",
    idea_viral: "Viral Potential",
    idea_generator_engine: "Idea Generator Engine"
  },
  ar: {
    home: "الرئيسية",
    channelAnalytics: "تحليل القناة",
    videoAnalytics: "فحص الفيديو",
    seoTools: "السيو الذكي",
    earningsLab: "مختبر الأرباح",
    liveCounter: "عداد مباشر",
    vphTool: "حاسبة السرعة",
    ideaGenerator: "مولد الأفكار",
    competitorAnalysis: "تحليل المنافسين",
    outliers: "كشف القيم الشاذة",
    planner: "خطة النمو",
    audienceDeepDive: "تحليل الجمهور العميق",
    audienceInsights: "غير مستخدم",
    imageGenerator: "ستوديو نانو بنانا",
    scriptWriter: "كاتب الاسكريبت المخضرم",
    history: "السجلات المحفوظة",
    guidelines: "دليل الاستخدام الشامل",
    trendForecasting: "التنبؤ بالتريند",
    thumbnailSimulator: "محاكي الصور المصغرة",
    videoTiming: "المجهر الزمني للفيديو",
    globalTiming: "أطلس التوقيت العالمي",
    searchPlaceholder: "ضع رابط القناة/الفيديو أو المعرف...",
    analyze: "تحليل",
    views: "مشاهدات",
    subscribers: "مشتركين",
    videos: "فيديوهات",
    country: "الدولة",
    created: "تاريخ الانضمام",
    channelAge: "عمر القناة",
    description: "",
    keywords: "الكلمات المفتاحية",
    copy: "نسخ",
    copied: "تم النسخ!",
    subscribe: "اشتراك",
    engagementRate: "معدل التفاعل",
    vph: "مشاهدات في الساعة",
    estimatedEarnings: "الأرباح التقديرية",
    seoScore: "نقاط السيو",
    titleGenerator: "مولد العناوين",
    moneyCalculator: "حاسبة الأرباح",
    days: "يوم",
    months: "شهر",
    years: "سنة",
    ago: "مضت",
    loading: "جاري المعالجة...",
    error: "خطأ في البيانات",
    channelNotFund: "لم يتم العثور على القناة",
    videoNotFound: "لم يتم العثور على الفيديو",
    enterUrl: "أدخل رابط يوتيوب صحيح",
    generate: "توليد",
    recommendation: "توصية",
    good: "جيد",
    bad: "يحتاج تحسين",
    excellent: "ممتاز",
    calcEarnings: "حساب الأرباح المتوقعة",
    daily: "يومياً",
    monthly: "شهرياً",
    yearly: "سنويأ",
    min: "أدنى",
    max: "أقصى",
    avg: "متوسط",
    compare: "مقارنة القنوات",
    vs: "ضد",
    bestTime: "أفضل وقت للنشر",
    exportPdf: "تصدير الخطة (PDF)",
    exportImage: "تصدير كصورة (PNG)",
    weeklyPlan: "الخطة الأسبوعية",
    potential: "الفرصة",
    likes: "إعجابات",
    comments: "تعليقات",
    descWords: "",
    perDay: "/ يوم",
    targetMarket: "السوق المستهدف",
    avgViewsPerVid: "مشاهدة/فيديو",
    publishedLabel: "تاريخ النشر",
    ageLabel: "العمر",
    targetKeywords: "الكلمات المستهدفة",
    optimizedTitles: "عناوين محسنة (50-60 حرف)",
    copyAllKeywords: "نسخ كل الكلمات",
    charsLabel: "حرف",
    useAiCheck: "استخدام ذكاء Gemini 3 Pro",
    healthScore: "صحة القناة",
    seo_title_length: "طول العنوان",
    seo_tag_depth: "قوة الوسوم",
    seo_description: "",
    seo_synergy: "تطابق الكلمات",
    seo_chars: "حرف",
    seo_tags_used: "وسم مستخدم",
    seo_words: "كلمة",
    seo_matches: "تطابق",
    analyzeVph: "حساب السرعة",
    currentVelocity: "السرعة الحالية",
    trendAnalysis: "تحليل الاتجاه",
    optimizationTips: "نصائح التحسين",
    totalWatchTime: "إجمالي وقت المشاهدة",
    trend_viral: "فيرال / متفجر 🚀",
    trend_rising: "صاعد / رائج 🔥",
    trend_stable: "مستقر / دائم ⚖️",
    trend_slow: "بطيء / متناقص 📉",
    tip_viral: "أداء استثنائي! قم بإنشاء فيديو متابعة فوراً لاستغلال هذه الحركة.",
    tip_rising: "زخم جيد. قم بالرد على كل تعليق لتنشيط إشارات التفاعل في الخوارزمية.",
    tip_stable: "حركة مستقرة. تأكد من أن شاشات النهاية تشير إلى فيديوهاتك الجديدة.",
    tip_slow: "السرعة منخفضة. جرب تغيير الصورة المصغرة أو تحديث العنوان ليكون أكثر جاذبية للنقر.",
    nicheIdentified: "التخصص المكتخصص",
    topCompetitors: "أبرز المنافسين الحقيقيين",
    strategicFocus: "نقاط القوة الاستراتيجية",
    competitorPlaceholder: "أدخل رابط قناتك. سيقوم الذكاء الاصطناعي بتحديد تخصصك وكشف المنافسين الفعليين.",
    selectToCompare: "اختر للمقارنة",
    benchmark: "مقارنة المحدد",
    comparisonTable: "جدول المقارنة",
    metric_label: "المقياس",
    you_label: "(أنت)",
    engagement_label: "معدل التفاعل",
    avg_views_label: "متوسط المشاهدات/فيديو",
    primaryMarket: "السوق الأساسي",
    highEngagement: "نافذة التفاعل العالي",
    preciseTime: "وقت النشر الدقيق",
    audienceDesc: "اكتشف متى ينشر صانع المحتوى بدقة، وتتبع الجدول الزمني بناءً على التوقيت المحلي للدولة.",
    globalUnset: "عالمي / غير محدد",
    fullSchedule: "الجدول الأسبوعي الكامل",
    scheduleTracker: "تتبع جدول الصانع",
    consistencyScore: "نقاط الالتزام",
    predictedUpload: "الفيديو القادم المتوقع",
    commonUploadTimes: "مواعيد الرفع المعتادة",
    timezoneDetected: "المنطقة الزمنية",
    uploadHabits: "عادات النشر",
    consistent: "ملتزم",
    random: "عشوائي",
    lvl_viral: "فيرال (خارق) 🔥",
    lvl_excellent: "ممتاز جداً 🚀",
    lvl_good: "جيد ✅",
    lvl_weak: "متوسط ⚠️",
    predictedAudience: "الجمهور المتوقع",
    male: "ذكور",
    female: "إناث",
    topDayLabel: "أفضل يوم",
    weeklyProtocol: "بروتول النمو الأسبوعي",
    focusGoal: "الهدف الأساسي",
    weeklyCommitment: "أتعهد بتنفيذ هذه الخطة لتنمية قناتي.",
    startPlan: "بدء خطة النمو",
    planDesc: "أدخل رابط قناتك. سيقوم النظام بتحليل نقاط الضعف وإنشاء جدول مهام أسبوعي لزيادة المشتركين.",
    goldenRatio: "النسبة الذهبية",
    noOutliers: "لم يتم اكتشاف فيديوهات شاذة.",
    outlierDesc: "اكتشف الفيديوهات التي حققت أداءً أفضل بـ 2x-10x من متوسط القناة.",
    trendingKeywords: "الكلمات الرائجة",
    aiIdeas: "أفكار بالذكاء الاصطناعي",
    useAiLabel: "استخدام ذكاء Gemini 3 Pro",
    contentDepth: "عمق المحتوى",
    minRevenue: "الربح الأدنى",
    maxRevenue: "الربح الأقصى",
    smartAlgo: "تحليل الخوارزمية الذكي",
    algoDesc: "بناءً على موقع القناة وتصنيف المحتوى، تم تحديد الـ CPM المتوقع.",
    titleAnalysis: "تحليل العنوان",
    cpmLabel: "سعر الألف ظهور",
    total: "الإجمالي",
    lifetime: "مدى الحياة",
    videoType: "فيديو",
    channelType: "قناة",
    viewOnYoutube: "مشاهدة على يوتيوب",
    healthScoreTitle: "صحة القناة والنظام البيئي",
    consistency: "الالتزام",
    engagement: "التفاعل",
    viralPotential: "القابلية للانتشار",
    action_ideas: "أفكار محتوى",
    action_competitors: "تجسس المنافسين",
    action_outliers: "كشف الفيديوهات الشاذة",
    action_planner: "خطة النمو",
    view_deep_analytics: "تحليل عميق",
    shortsAnalysis: "تحليل الشورتس (Shorts)",
    shortsEngagementDesc: "تتطلب فيديوهات الشورتس معدل تفاعل أعلى (>5%) للظهور في خوارزمية Shorts Feed.",
    monetizationStatus: "حالة تحقيق الربح",
    eligible: "مؤهلة للربح",
    notEligible: "الشروط غير مكتملة",
    ypp_requirements: "متطلبات الربح (YPP)",
    req_subs_title: "1,000 مشترك",
    req_hours_title: "4,000 ساعة مشاهدة علنية",
    req_hours_title_short: "4,000 ساعة",
    req_shorts_title: "10 مليون مشاهدة شورتس",
    or: "أو",
    met: "مكتمل",
    not_met: "ناقص",
    chat_welcome: "أهلاً! أنا مساعد مُثقّف الذكي. اسألني عن ترندات يوتيوب، تحليل قناتك، أو أي شيء في العالم!",
    chat_placeholder: "اسأل عن قناتك، أسعار الإعلانات، أو استراتيجيات...",
    chat_assistant: "مساعد مُثقّف",
    chat_thinking: "جاري التفكير والبحث...",
    mode_fast: "السريع",
    mode_think: "المفكر",
    mode_search: "الباحث",
    chat_copy: "نسخ",
    chat_reply: "رد",
    chat_quote: "اقتباس المحدد",
    chat_replying_to: "الرد على...",
    chat_clear_confirm: "هل أنت متأكد من حذف سجل المحادثة؟",
    chat_history_label: "شات AI",
    chat_new_chat: "محادثة جديدة",
    chat_delete_msg: "حذف الرسالة",
    brain_mode: "وضع الدماغ (المسح العميق)",
    brain_active: "العقل المدبر نشط",
    deep_scan_start: "جاري بدء بروتول المسح الشامل...",
    fetching_channel: "جاري جلب هيكلية القناة...",
    fetching_videos: "تحليل سرعة المحتوى الأخير...",
    calculating_growth: "حساب خوارزميات النمو...",
    report_ready: "تم إنشاء التقرير الاستراتيجي.",
    download_report: "تحميل التقرير",
    img_gen_title: "ستوديو نانو بنانا",
    img_gen_desc: "اصنع صور مصغرة فيرال لليوتيوب أو صور احترافية باستخدام نموذج Gemini 2.5 Flash Image.",
    img_tab_generate: "توليد",
    img_tab_edit: "المحرر السحري",
    img_upload_label: "صورة الخلفية",
    img_upload_desc: "ستكون هذه هي الخلفية أو الموضوع الرئيسي.",
    img_add_asset: "إضافة عنصر / كائن",
    img_add_asset_desc: "ارفع صورة ثانية (مثل شعار أو شخصية) لدمجها.",
    img_add_asset_2: "إضافة عنصر آخر",
    chat_img_normal: "صورة عادية",
    chat_img_thumbnail: "صورة مصغرة لليوتيوب",
    chat_img_generating: "جاري المعالجة...",
    chat_img_placeholder: "أوصف الصورة أو التعديل المطلوب...",
    download_image: "تحميل الصورة",
    select_ratio: "الأبعاد المطلوبة",
    export_options: "خيارات التصدير",
    export_2k: "تحسين لـ 2K (QHD)",
    export_4k: "تحسين لـ 4K (UHD)",
    enhancing_label: "جاري التحسين ورفع الدقة...",
    download_ready: "الصورة جاهزة",
    script_title: "كاتب الاسكريبت المخضرم",
    script_desc: "توليد نصوص فيديوهات بشرية، متصدرة للسيو، بأي لغة (ومتخصص في جميع اللهجات العربية).",
    script_placeholder: "أدخل عنوان الفيديو، الموضوع، أو الفكرة...",
    script_duration_label: "المدة المستهدفة",
    script_tone_label: "نبرة الاسكريبت",
    script_lang_label: "اللغة / اللهجة",
    script_hook_label: "استراتيجية الخطفة (Hook)",
    script_custom_hook_placeholder: "اكتب الجملة الافتتاحية المحددة هنا...",
    script_tone_serious: "جدي واحترافي",
    script_tone_funny: "كوميدي وترفيهي",
    script_tone_story: "سرد قصصي (Storytelling)",
    script_tone_educational: "تعليمي (خطوة بخطوة)",
    script_tone_motivational: "تحفيزي وملهم",
    script_tone_sarcastic: "ساخر وكوميدي أسود",
    script_tone_mysterious: "غامض ومثير للفضول",
    script_tone_emotional: "عاطفي ومؤثر",
    script_tone_fast: "سريع (أسلوب تيك توك)",
    script_tone_calm: "هادئ ومريح (ASMR)",
    script_tone_controversial: "جدلي/نقاش حاد",
    script_tone_dramatic: "درامي سينمائي",
    script_tone_casual: "عفوي / فلوج",
    script_tone_professional: "رسمي / شركات",
    script_tone_urgent: "عاجل / تحذيري",
    script_hook_none: "افتراضي / بدون",
    script_hook_question: "سؤال صادم",
    script_hook_fact: "حقيقة غريبة",
    script_hook_neg: "إلحاح سلبي (توقف عن فعل هذا)",
    script_hook_story: "بداية قصة (الساعة كانت 3 الفجر...)",
    script_hook_compare: "مقارنة (س ضد ص)",
    script_lang_egy: "العربية (العامية المصرية)",
    script_lang_sa: "العربية (السعودية - خليجي)",
    script_lang_shami: "العربية (الشامية - لبناني/سوري)",
    script_lang_maghreb: "العربية (المغربية - الدارجة)",
    script_lang_iraqi: "العربية (العراقية)",
    script_lang_yemen: "العربية (اليمنية)",
    script_lang_fusha: "العربية (الفصحى)",
    script_lang_en: "الإنجليزية (عالمي)",
    script_lang_es: "الإسبانية",
    script_lang_fr: "الفرنسية",
    script_lang_de: "الألمانية",
    script_lang_hi: "الهندية",
    script_lang_ru: "الروسية",
    script_lang_pt: "البرتغالية",
    script_lang_zh: "الصينية",
    script_lang_jp: "اليابانية",
    script_lang_kr: "الكورية",
    script_lang_tr: "التركية",
    script_duration_short: "قصير (1-3 دقائق)",
    script_duration_medium: "متوسط (5-8 دقائق)",
    script_duration_long: "طويل (10-20 دقيقة)",
    script_generating: "جاري كتابة الاسكريبت...",
    script_section_title: "عنوان SEO متصدر",
    script_section_desc: "وصف SEO دقيق",
    script_section_body: "اسكريبت الفيديو",
    script_copy_all: "نسخ الكل",
    script_show_notes: "إظهار تعليمات المخرج",
    script_hide_notes: "إخفاء تعليمات المخرج",
    aud_segments: "شرائح الجمهور",
    aud_new: "المشاهدون الجدد",
    aud_casual: "المشاهدون العاديون",
    aud_loyal: "المشاهدون المنتظمون",
    aud_formats: "تفضيلات التنسيق",
    aud_devices: "الأجهزة المستخدمة",
    aud_geo: "أهم المناطق",
    aud_online: "وقت نشاط المشاهدين",
    aud_also_watch: "قنوات يشاهدها جمهورك",
    aud_growth_drivers: "فيديوهات توسيع الجمهور",
    aud_desc: "تحليل عميق لشرائح الجمهور، السلوكيات، والديموغرافيا.",
    history_title: "السجلات المحفوظة",
    history_desc: "سجل دائم لجميع تحليلاتك. لا يتم الحذف أبداً إلا بطلبك.",
    clear_history: "حذف السجل بالكامل",
    no_history: "لا توجد سجلات بعد. ابدأ التحليل الآن!",
    filter_all: "كل السجلات",
    view_result: "عرض النتيجة",
    delete: "حذف",
    renew_record: "تجديد لمدة سنة",
    expires_in: "ينتهي خلال:",
    days_left: "يوم متبقي",
    record_renewed: "تم تجديد السجل!",
    tooltip_live_input: "يقبل رابط القناة، المعرف ID، أو المعرف الشخصي Handle (مثل @name).",
    tooltip_sub_count: "اتصال مباشر مع خوادم يوتيوب. يتم التحديث كل ثانية واحدة تلقائياً.",
    tooltip_channel_stats: "إجمالي الإحصائيات المتراكمة منذ إنشاء القناة.",
    tooltip_channel_age: "حساب دقيق للوقت المنقضي منذ تاريخ إنشاء القناة المسجل.",
    tooltip_video_input: "يقبل رابط الفيديو، المعرف ID، أو روابط الفيديوهات القصيرة Shorts.",
    tooltip_vph: "المشاهدات في الساعة: مقياس للسرعة يحسب بقسمة إجمالي المشاهدات على عدد الساعات منذ النشر.",
    tooltip_engagement: "مقياس التفاعل: (الإعجابات + التعليقات) / المشاهدات. يوضح مدى نشاط الجمهور.",
    tooltip_seo_score: "تحليل خوارزمي لطول العنوان، الكلمات الجذابة، وقابلية النقر.",
    tooltip_tags: "الوسوم المخفية (Tags) التي تم استخراجها من الكود المصدري للفيديو.",
    tooltip_earnings_input: "أدخل رابط فيديو أو قناة ليتم اكتشاف التخصص والدولة تلقائياً.",
    tooltip_cpm: "التكلفة لكل ألف ظهور: تقدير بناءً على دولة المشاهد (القوة الشرائية) وتخصص المحتوى.",
    tooltip_est_earnings: "الأرباح المتوقعة: تفترض أن 60% من المشاهدات تعرض إعلانات. الأرباح الحقيقية تعتمد على وقت المشاهدة.",
    tooltip_seo_generator: "يولد عناوين ذات معدل نقر عالي (CTR) باستخدام أنماط لغوية فيرال.",
    tooltip_watch_time: "مجموع الوقت الذي قضاه جميع المشاهدين في مشاهدة هذا الفيديو (المشاهدات × المدة).",
    tooltip_min_rev: "تقدير متحفظ يعتمد على معدلات ملء إعلانات منخفضة.",
    tooltip_max_rev: "تقدير متفائل يفترض وقت مشاهدة عالي وإعلانات متميزة.",
    tooltip_algo_calc: "طريقة الحساب: المشاهدات × نسبة ظهور الإعلانات (60%) × (CPM ÷ 1000).",
    tooltip_trend_logic: "يتم تحديد الاتجاه من خلال ربط سرعة المشاهدات الحالية بعمر الفيديو.",
    vt_exact_pub: "توقيت النشر الدقيق",
    vt_exact_pub_desc: "تحليل لحظة أرشفة الفيديو على خوادم جوجل بالملي ثانية.",
    vt_viewer_flow: "محاكي تدفق الجمهور",
    vt_viewer_flow_desc: "تقدير خوارزمي لوصول المشاهدين الحقيقيين منذ لحظة الرفع.",
    vt_peak_time: "قمة حركة المرور المتوقعة",
    vt_retention_window: "نافذة الاحتفاظ الذهبية",
    vt_algo_verdict: "حكم الخوارزمية على التوقيت",
    vt_pacing_score: "نقاط سرعة الإيقاع",
    script_duration_15s: "15 ثانية (Shorts)",
    script_duration_60s: "60 ثانية (عادي)",
    script_duration_5m: "5 دقائق (عميق)",
    script_duration_10m: "10 دقائق (وثائقي)",
    script_tone_energetic: "حماسي وتفاعلي",
    script_tone_professional_calm: "احترافي وهادئ",
    script_tone_storytelling_emotional: "قصصي وعاطفي",
    script_tone_educational_clear: "تعليمي وواضح",
    script_hook_curiosity: "سؤال فضولي",
    script_hook_shocking: "حقيقة صادمة",
    script_hook_result: "النتيجة أولاً",
    script_hook_story_media: "بداية قصة مثيرة",
    script_seo_low: "منخفض",
    script_seo_balanced: "متوازن",
    script_seo_high: "مرتفع",
    script_neural_engine: "المحرك العصبي للسكربتات",
    script_viral_2026: "كاتب فيروسي 2026",
    planner_goal: "هدف النمو",
    planner_style: "نمط المحتوى",
    planner_style_mixed: "مختلط (قصير + طويل)",
    planner_style_shorts: "فيديوهات قصيرة فقط",
    planner_style_long: "فيديوهات طويلة فقط",
    planner_military_grade: "تصنيف عسكري",
    planner_exponential: "نمو أسي",
    planner_secure: "تحليل آمن",
    seo_focus: "تركيز السيو",
    seo_region: "المنطقة المستهدفة",
    seo_region_global: "عالمي (Global)",
    seo_region_mena: "الشرق الأوسط (MENA)",
    seo_region_us_eu: "أمريكا وأوروبا",
    seo_region_asia: "آسيا",
    seo_engine: "محرك السيو العصبي",
    idea_niche: "التخصص",
    idea_platform: "المنصة",
    idea_trending: "رائج الآن",
    idea_evergreen: "محتوى دائم",
    idea_viral: "فيرال (خارق)",
    idea_generator_engine: "محرك توليد الأفكار"
  }
};
